# Generated by Django 5.0.6 on 2025-08-26 21:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('ERROR', 'Error')], default='PENDING', max_length=12)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('mime', models.CharField(default='video/mp4', max_length=64)),
                ('result_mp4', models.BinaryField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
